### ISSUE TITLE
Option to change keyword from default "bm"

### ISSUE THREAD

**Issue by menace97** [alvinhochun/chrome-bookmark-search#11]
Suggestion:
Add an option to change the keyword used to search for bookmarks from "bm" to a user-defined keyword

Note:
A simple single letter "**b**" would be fantastic as a default.

Thanks for your consideration!

**Comment by alvinhochun** [comment]
That is not possible. It is a limitation of Chrome.
.
It has to be changed in the manifest directly, which means you'll have to download the source, modify it, then load the unpacked extension via the developer option.

Duplicates: #3, #4
