### ISSUE TITLE
Incompatible with Vivaldi

### ISSUE THREAD

**Issue by lugotal** [alvinhochun/chrome-bookmark-search#15]
Hi!

I guess this is more of a feature request.
Currently, the extension seems to be incompatible with Vivaldi, a Chromium-based browser which comes with built-in Chrome extension support.

When typing the shortcut, it doesn't activate the extension:
![image](https://user-images.githubusercontent.com/9104054/112332008-adf0a600-8cb9-11eb-82d3-3ae4951fec4f.png)

I have checked and enabled available settings:
![image](https://user-images.githubusercontent.com/9104054/112332551-1f305900-8cba-11eb-9ea6-80eebee5bcc8.png)

Would it be possible to add compatibility with Vivaldi? Thanks.

**Comment by alvinhochun** [comment]
It might be that Vivaldi does not support custom search keywords in extensions. Even though it may be using the Chromium engine, its user interface may not be sharing the same code as Chromium. You might want to ask the Vivaldi community and developers for advice.

I don't use Vivaldi so I probably won't look into this, but if you figure out the changes needed to make it work I would be glad to accept a PR.

**Comment by lugotal** [comment]
Ah, that's what I was afraid of. I checked just now and yeah, the chrome element does not have an omnibox attribute and I wasn't able to find anything similar - so there's probably no chance of making this work.

A shame, really. Thanks anyway! This can be closed. :)
