### ISSUE TITLE
Show only bookmarks when you are in bookmark search mode

### ISSUE THREAD

**Issue by inson1** [alvinhochun/chrome-bookmark-search#20]
Could it be done?

**Comment by alvinhochun** [comment]
Do you mean Chrome lists other search suggestions below the bookmark search extension results? I'm afraid there is no way to customize this behaviour as it is controlled by Chrome.

**Comment by inson1** [comment]
Yes. Oh ok.

**Comment by inson1** [comment]
Btw Brave can do that even without extension
