### ISSUE TITLE
custom keywords

### ISSUE THREAD

**Issue by tarla** [alvinhochun/chrome-bookmark-search#3]
would be nice to set custom keywords to omnibox.

p.s.: I read the [docs](https://developer.chrome.com/extensions/omnibox) and didn't find a way to do it, if it exists, I would be glad to submit a PR. Thanks!

**Comment by alvinhochun** [comment]
It has to be changed in the manifest directly, which means you'll have to download the source, modify it, then load the unpacked extension via the developer option.

**Comment by tarla** [comment]
I did it in a fork. Thanks! It's an awesome project.

**Comment by alvinhochun** [comment]
It really is just something that I threw together as an experiment. Glad you find it useful.
