### ISSUE TITLE
add option to change keyword from "bm"

### ISSUE THREAD

**Issue by sloanlance** [alvinhochun/chrome-bookmark-search#4]
Please add an option to let users change the activation keyword from "bm" to something else.  It would help to eliminate conflicts with other extensions or user-defined search engines.  It would also allow users to pick a keyword that's more comfortable for them.

**Comment by alvinhochun** [comment]
That is not possible. It is a limitation of Chrome.
.
It has to be changed in the manifest directly, which means you'll have to download the source, modify it, then load the unpacked extension via the developer option.

See #3

**Comment by sloanlance** [comment]
Too bad.  I just tested what would happen if there was a pre-existing search engine with the keyword "bm".  The pre-existing one will be used, not Bookmark Search.
