### ISSUE TITLE
can you make the app case insensitive

### ISSUE THREAD

**Issue by kajodowe** [alvinhochun/chrome-bookmark-search#6]
Nice app -- thanks for writing it. Would like to see the search have an option to make the results not case sensitive. Currently the results are case sensitive so that if I capitalized a word in the bookmark I created I must capitalize it in the search query. 

-Allen

**Comment by alvinhochun** [comment]
Hm I don't think it is case sensitive at all.

If you choose to use the "Chrome built-in search" it should output the same results as in the Bookmark Manager page. Do you get the result when searching there? (chrome://bookmarks/)

Even the "Bookmark Search version 2" algorithm should get similar results.

**Comment by kajodowe** [comment]
You are correct -- I was wrong. I retested by creating a link with the word
"Test" and then typed "bm test" and the bookmark was retrieved. Sorry for
my mistake. Great app -- very handy for me because I have around 5,000
bookmarks!

-Allen
